### ISSUE TITLE
Скрипт не поддерживается на системах без FHS

### ISSUE THREAD

**Issue by LennyLizowzskiy** [Shedou/Chimbalix#3]
Здравствуйте!!! Я использую NixOS!!! Сами вы его выбрали или за вас, но это лучший дистрибутив из оставшихся. Я был так горд за NixOS, что сам решил начать использовать её.

Я так устал от того что во всех линуксах так много терминалов и был очень рад узнать про этот скрипт

Так вот, на ней скрипт не работает, потому что на ней бинарники находятся не в `/bin/`. Прошу исправить эту проблему проверкой `$PATH`

**Comment by Shedou** [comment]
Вероятно это займет некоторое время, просто я не имею опыта с NixOS :)
![Screenshot_2023-12-04_22-27-17](https://github.com/Shedou/Chimbalix/assets/19572158/911909e5-d7e8-47e6-9b49-11af663117f6)

**Comment by Shedou** [comment]
Скрипт конечно теперь можно запустить в том числе и в NixOS, только вот для данной ОС желательно другой скрипт писать чтобы всё работало "с двух кликов", пока что я не планирую этим заниматься, тем более не знаком особо с NixOS чтобы полностью адаптировать существующий скрипт.

![Screenshot_2023-12-05_12-59-49](https://github.com/Shedou/Chimbalix/assets/19572158/dbf113ff-c90e-4141-b972-8f9adf6a87f3)

**Comment by LennyLizowzskiy** [comment]
Спасибо за то что смогли сделать хотя бы это. Понимаю, что поддержку таких необычных систем добавить сложно и в этом в целом мало смысла, т.к. все используют стандартные Федоры и Арчи. Закрываю ишью
