### ISSUE TITLE
Нет поддержки терминала `wezterm`

### ISSUE THREAD

**Issue by LennyLizowzskiy** [Shedou/Chimbalix#4]
Добрый день!!

У меня на другой системе не работает скрипт потому что я использую терминал Wezterm! Он написан на Расте и очень крутой, но у вас его нет. Пожалуйста, добавьте

**Comment by Shedou** [comment]
Добавил проверку наличия данного терминала
![Screenshot_2023-12-04_22-22-09](https://github.com/Shedou/Chimbalix/assets/19572158/65ea657f-203b-4350-b4c1-a5560a6196c6)

**Comment by LennyLizowzskiy** [comment]
Закрываю ишью
