### ISSUE TITLE
Нет поддержки других шеллов

### ISSUE THREAD

**Issue by LennyLizowzskiy** [Shedou/Chimbalix#5]
Я ещё и использую шелл fish, поэтому мне приходится запускать ваши скрипты через bash отдельно. Прошу добавить поддержку fish!

**Comment by Shedou** [comment]
Скрипт рассчитан на работу с эмуляторами терминала, если даже и вписать fish для вызова командой "terminal", это скорее всего будет приводить к проблемам, так как сам по себе fish не является эмулятором терминала, потому не вижу смысла его подсвечивать в списке доступных терминалов...

Но если очень хочется попробовать, всегда можно ввести вручную название терминала, даже если он не подсвечен в списке доступных, или использовать аргумент custom вместо set, тогда можно будет ввести путь к любому файлу.

**Comment by LennyLizowzskiy** [comment]
Закрываю ишью, проблема была на моей стороне
